---
title: "Active Listening"
author: "Ryan Estrellado"
date: "2/1/2018"
output: html_document
---

Wikipedia has a pretty good [definition of active listening](https://en.wikipedia.org/wiki/Active_listening): 

>Active listening is a communication technique that is used in counseling, training, and conflict resolution. It requires that the listener fully concentrate, understand, respond and then remember what is being said. 

So how does active listening help us succeed in our role as facilitators of discussion groups or when supporting people one on one? 


## Listen to Understand

The goal of active listening is to build understanding. Building understanding is useful because it builds trust and safety, which in turn are useful in progressing towards some common goal. If the speaker feels judged or thinks they are being criticised, it can trigger the fight or flight instinct. When this happens, the speaker may push back or change the subject, neither of which are conducive to building understanding. 

Here are some things that get in the way of listening for understanding: 

- Formulating responses instead of listening 
- Interrupting the speaker 
- Speaking for too long without allowing the speaker a chance to respond 
- Starting with the assumption that you need to solve the speaker's problem 
- Voicing disagreement at every point of disagreement 
- The belief that understanding and disagreeing are mutually exclusive 


## Ways to Practice  

Here are some ways that we can practice active listening daily: 

**Active Listening Lucky Charm** 

Use a visual or tactile trigger, like a bracelet or a small object in your pocket as a reminder to break from talking and begin listening for understanding. This is most helpful when the object is only carried for this purpose alone. 

**Find Your Baseline Skill** 

Pick at least one interaction a day where you resolve to listen, talking only when you need to check your understanding of the speaker's point of view or when the speaker asks you a question. This is hard work, so if that is too difficult, try scaling the challenge back by resolving to listen for a few casual verbal exchanges. Then stretch your skill by working up to entire conversations. The good news is most people enjoy sharing, which means you'll have plenty of opportunities to listen. 

**Develop Your Go To Language for Clarification**

One of the goals of a conversation is to build understanding, so practice developing self awareness of when something the speaker said is not clear to you. Then develop your own safe and authentic ways to check in about your understanding. Here's an example of one I use frequently: 

>Before you go on, I just want to make sure I understand what you're saying. Earlier you said that he annoys you when he does that. Did you mean your teacher or your classmate? Ah, ok got it. Sorry just wanted to make sure. Ok so go on- you were talking about...

**Keep Group Goals In Mind**

Listening while you are facilitating a group conversation can be difficult, because you want to build a safe environment but you also want to manage the time and attention of your group. One way to do that is make decisions about whether the speaker's ideas connect back to what the group is trying to learn together. If it does, listen for a bit and **make sure they know you understand what they are communicating**. Then connect it back to the conversation topic. If the speaker is discussing something that is off topic, listen for a bit and **make sure they know you understand what they are communicating**. Then bring the group back on topic by saying something like "I want to understand your point of view better and I think it deserves its own time. I'd like to move on but I'm open to talking more after the group."


# More Resources 

- [Wikipedia: Active listening](https://en.wikipedia.org/wiki/Active_listening)  
- [Active Listening On MindTools](https://www.mindtools.com/CommSkll/ActiveListening.htm)  
- [Video: Being a Good Listener](https://youtu.be/-BdbiZcNBXg)